// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFoFFup8YmAl7mXqbedkyMLaakhqvl6Vo',
    appId: '1:645670203573:web:8c1eef70c37373bc2c4efc',
    messagingSenderId: '645670203573',
    projectId: 'clothbridge2',
    authDomain: 'clothbridge2.firebaseapp.com',
    storageBucket: 'clothbridge2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOiBy7Tx8acA7Hqr63uU-1GENz_TRG2YU',
    appId: '1:645670203573:android:06d7ea10bbe19e562c4efc',
    messagingSenderId: '645670203573',
    projectId: 'clothbridge2',
    storageBucket: 'clothbridge2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1x7sC3LfRZko9tjUt2xE4QcfhQv9GfvI',
    appId: '1:645670203573:ios:16045322264f51822c4efc',
    messagingSenderId: '645670203573',
    projectId: 'clothbridge2',
    storageBucket: 'clothbridge2.firebasestorage.app',
    iosBundleId: 'com.example.clothbridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1x7sC3LfRZko9tjUt2xE4QcfhQv9GfvI',
    appId: '1:645670203573:ios:16045322264f51822c4efc',
    messagingSenderId: '645670203573',
    projectId: 'clothbridge2',
    storageBucket: 'clothbridge2.firebasestorage.app',
    iosBundleId: 'com.example.clothbridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFoFFup8YmAl7mXqbedkyMLaakhqvl6Vo',
    appId: '1:645670203573:web:d4c1b9dabc15647e2c4efc',
    messagingSenderId: '645670203573',
    projectId: 'clothbridge2',
    authDomain: 'clothbridge2.firebaseapp.com',
    storageBucket: 'clothbridge2.firebasestorage.app',
  );
}
